<a href="/ecommerce/tipo-enderecos/create"><input type="button" class="btn btn-primary" value="Novo tipo endereço" title="Inserir novo tipo de endereço."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($tipoEnderecos as $tipoEndereco) {
                ?>
                <tr>
                    <td><?= $tipoEndereco->id_tipo_endereco; ?></td>
                    <td><?= $tipoEndereco->descricao; ?></td>

                    <td> <a href="/ecommerce/tipo-enderecos/update/id/<?= $tipoEndereco->id_tipo_endereco ?>">
                            <span class="glyphicon glyphicon-pencil" title="Excluir registro"></span> </a></td>

                    <td> <a href="/ecommerce/tipo-enderecos/delete/id/<?= $tipoEndereco->id_tipo_endereco ?>">
                            <span class="glyphicon glyphicon-trash" title="Editar registro"></span> </a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $tipoEnderecos, 'sliding', 'partial/paginator.phtml', array(
    'route' => 'tipoEndereco'
        )
);
?>
