<?php echo $this->doctype(); ?>

<html lang="pt-br">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sistema de autenticação ' . $this->translate('Sistema de autenticação'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                ->prependStylesheet($this->basePath() . '/css/style_crs.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/themes/base/jquery-ui.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/main.js')
                ->prependFile($this->basePath() . '/js/jquery.maskedinput.js')
                ->prependFile($this->basePath() . '/js/jquery-ui.js')
              	->prependFile($this->basePath() . '/js/jquery.min.js')
        ?>
        <style type="text/css">
            body {
                background-image: none;
                padding-top: 40px;
                padding-bottom: 40px;
                background-color: #f5f5f5;
                
            }

            .form-signin {
                max-width: 300px;
                padding: 19px 29px 29px;
                margin: 0 auto 20px;
                background-color: #fff;
                border: 1px solid #e5e5e5;
                -webkit-border-radius: 5px;
                -moz-border-radius: 5px;
                border-radius: 5px;
                -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
                box-shadow: 0 1px 2px rgba(0,0,0,.05);
            }
            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }
            .form-signin input[type="text"],
            .form-signin input[type="password"] {
                font-size: 16px;
                height: auto;
                margin-bottom: 15px;
                padding: 7px 9px;
            }

        </style>
    </head>

    <body >

        <!-- Msg Success -->

        <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
            <div class="success_msg">
                <?php
                foreach ($this->flashMessenger()->getSuccessMessages() as $msg) {
                    echo $msg;
                }
                ?>
            </div>
        <?php } ?>

        <!-- Msg Error -->

        <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
            <div class="error_msg">
                <?php
                foreach ($this->flashMessenger()->getErrorMessages() as $msg) {
                    echo $msg;
                }
                ?>
            </div>
        <?php } ?>

        <!-- Msg Warning -->   

        <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
            <div class="warning_msg">
                <?php
                foreach ($this->flashMessenger()->getInfoMessages() as $msg) {
                    echo $msg;
                }
                ?>
            </div>
        <?php } ?>

        <div class="container">
            <?php echo $this->content; ?>
        </div>


        <!-- /container -->
        <?php echo $this->inlineScript() ?>
        <div class="footer">
            <p>&copy; Centro de Residência em Software 2013</p>
        </div>
    </body>
</html>
