<h1>Categoria</h1>
<a href="/admin/categorias/save"><input type="button" 
   class="btn btn-primary" value="Nova categoria" 
   title="Inserir nova categoria."></a>	
<br><br>
<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr class="tabela">
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($categorias as $categoria) {
            ?>
                <tr>
                    <td><?= $categoria->descricao; ?></td>
                    <td> 
                        <a href="/admin/categorias/save/id/<?= $categoria->id_categoria ?>">
                        <span class="glyphicon glyphicon-pencil" 
                        title="Editar registro"></span> </a>

                        <a href="/admin/categorias/delete/id/<?php echo 
                        $categoria->id_categoria ?>"
                        onclick= "return confirm('Deseja excluir este registro?');">
                        <span class="glyphicon glyphicon-trash" 
                        title="Editar registro"></span> </a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php
    echo $this->paginationControl(
        $categorias, 'sliding', 'partial/paginator.phtml', 
        array(
            'route' => 'categorias'
        )
    );
?>
