<h1>Endereços</h1>
<a href="/admin/enderecos/save"><input type="button" 
   class="btn btn-primary" value="Novo Endereço" 
   title="Inserir novo endereço."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr class="tabela">
                <th>Nome do destinatário</th>
                <th>Telefone</th>
                <th>CEP</th>
                <th>Endereco</th>
                <th>Numero</th>
                <th>Bairro</th>
                <th>Cidade</th>
                <th>Estado</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($enderecos as $endereco) {
            ?>
                <tr>

                    <td><?= $endereco->nome_do_destinatario; ?></td>
                    <td><?= $endereco->telefone; ?></td>
                    <td><?= $endereco->cep; ?></td>
                    <td><?= $endereco->endereco; ?></td>
                    <td><?= $endereco->numero; ?></td>
                    <td><?= $endereco->bairro; ?></td>
                    <td><?= $endereco->cidade; ?></td>
                    <td><?= $endereco->estado; ?></td>

                    <td> 
                        <a href="/admin/enderecos/save/id/<?= $endereco->id_endereco ?>">
                            <span class="glyphicon glyphicon-pencil" title="Editar registro"></span> </a>

                        <a href="/admin/enderecos/delete/id/<?= $endereco->id_endereco ?>"
                        onclick= "return confirm('Deseja excluir este registro?');">
                        <span class="glyphicon glyphicon-trash" title="Editar registro"></span> </a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>
<?php
echo $this->paginationControl(
        $enderecos, 'sliding', 'partial/paginator.phtml', array(
    'route' => 'produtos'
        )
);
?>