<a href="/admin/produtos/create"><input type="button" 
 class="btn btn-primary" value="Novo Produto" title="Inserir novo produto."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr>
                <th>Foto</th>
                <th>Nome</th>
                <th>Descrição</th>
                <th>Marca</th>
                <th>Modelo</th>
                <th>Sub Categoria</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($produtos as $produto) {
                ?>
                <tr>
                    <td>
                        <img class="img"  src="/img/photos_produtos/thumb/<?= $produto->url_photo  ?>" />
                    </td>
                    <td><?= $produto->nome; ?></td>
                    <td><?= $produto->descricao; ?></td>
                    <td><?= $produto->marca->descricao; ?></td>
                    <td><?= $produto->modelo->descricao; ?></td>
                    <td><?= $produto->subcategoria->descricao; ?></td>
                    <td><?= $produto->valor; ?></td>

                    <td> <a href="/admin/produtos/update/id/<?= $produto->id_produto ?>">
                        <span class="glyphicon glyphicon-pencil" title="Editar registro"></span> </a>

                         <a href="/admin/produtos/delete/id/<?= $produto->id_produto ?>">
                            <span class="glyphicon glyphicon-trash" title="Excluir registro"></span> </a>
                             <a href="/admin/produtos/visualizar/id/<?= $produto->id_produto ?>">
                                <span class="glyphicon glyphicon-eye-open" title="Vizualizar registro"></span> </a></td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div>
                <?php
                echo $this->paginationControl(
                    $produtos, 'sliding', 'partial/paginator.phtml', array(
                        'route' => 'produtos'
                        )
                    );
                    ?>
