<a href="/ecommerce/categorias/create">Nova categoria</a>
<table class="table">
    <thead>
        <tr>
            <th>Id</th>
            <th>Descrição</th>
        </tr>
    </thead>
    <tbody>
        <?php
        foreach ($categorias as $categoria) {
            ?>
            <tr>
                <td><?= $categoria->id_categoria; ?></td>
                <td><?= $categoria->descricao; ?></td>
                <td> <a href="/ecommerce/categorias/update/id/<?= $categoria->id_categoria ?>">
                        <span class="glyphicon glyphicon-pencil" title="Excluir registro"></span> </a></td>

                <td> <a href="/ecommerce/categorias/delete/id/<?= $categoria->id_categoria ?>">
                        <span class="glyphicon glyphicon-trash" title="Editar registro"></span> </a></td>

            </tr>

        <?php } ?>
    </tbody>
</table>

<?php
echo $this->paginationControl(
        $categorias, 'sliding', 'partial/paginator.phtml', array(
    'route' => 'categorias'
        )
);
?>
