<h1>Tipo de endereço</h1>
<a href="/admin/tipo-enderecos/save"><input type="button" 
    class="btn btn-primary" value="Novo tipo de endereço" 
    title="Inserir novo tipo de endereço."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr class="tabela">
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($tipoEnderecos as $tipoEndereco) {
            ?>
            <tr>
                <td><?php echo $tipoEndereco->descricao; ?></td>

                <td>
                    <a href="/admin/tipo-enderecos/save/id/<?= $tipoEndereco->id_tipo_endereco ?>">
                    <span class="glyphicon glyphicon-pencil" 
                    title="Editar registro"></span></a>

                     <a href="/admin/tipo-enderecos/delete/id/<?= $tipoEndereco->id_tipo_endereco ?>"
                     onclick= "return confirm('Deseja excluir este registro?');">
                    <span class="glyphicon glyphicon-trash" 
                    title="Excluir registro"></span> </a>
                </td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
    $tipoEnderecos, 'sliding', 'partial/paginator.phtml', array(
    'route' => 'tipoEndereco'
        )
);
?>
