<a href="/ecommerce/sub-categorias/create"><input type="button" class="btn btn-primary" value="Nova subcategoria" title="Inserir uma nova subcategoria."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($subCategorias as $subCategoria) {
                ?>
                <tr>
                    <td><?= $subCategoria->id_sub_categoria; ?></td>
                    <td><?= $subCategoria->descricao; ?></td>

                    <td> <a href="/ecommerce/sub-categorias/update/id/<?= $subCategoria->id_sub_categoria ?>">
                            <span class="glyphicon glyphicon-pencil" title="Excluir registro"></span> </a></td>

                    <td> <a href="/ecommerce/sub-categorias/delete/id/<?= $subCategoria->id_sub_categoria ?>">
                            <span class="glyphicon glyphicon-trash" title="Editar registro"></span> </a></td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
        $subCategorias, 'sliding', 'partial/paginator.phtml', array(
    'route' => 'subCategoria'
        )
);
?>
