<h1>Index Application</h1>
    
<a href="/ecommerce/produtos/index"><input type="button" class="btn btn-primary" value="Produtos" title="Inserir novo produto."></a>	


<a href="/ecommerce/marcas/index"><input type="button" class="btn btn-primary" value="Marcas" title="Inserir novo produto."></a>	


<a href="/ecommerce/categorias/index"><input type="button" class="btn btn-primary" value="Categorias" title="Inserir novo produto."></a>	

<a href="/ecommerce/tipo-enderecos/index"><input type="button" class="btn btn-primary" value="Tipo endereco" title="Inserir novo produto."></a>	


<a href="/ecommerce/sub-categorias/index"><input type="button" class="btn btn-primary" value="Subcategoria" title="Inserir novo produto."></a>	

