<!--
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<title></title>
</head>
<body>
<div class="container">

       <div class="row conteudo">
       		<h1 class="h"><a href=""> Informática</a> > <a href="">notebook</a></h1>
         <div class="col-sm-5 col-md-6">
           <div class="thumbnail">
             <img src="imagens/Notebook-Acer-especial-da-Microsoft-bg.jpg"  alt="" class="img-rounded" >
             <div class="caption">
               <h3>Pc Dell Optples I7 asdasd fgfdgdf</h3>
               <p>R$ 3.250,00</p>
               <p>Ou 10X de 325,00 sem juro</p>
               <p><a class="btn btn-success" href="#" role="button">Comprar</a></p>
               
             </div>
           </div>
         </div>
		
         <div class="col-sm-5 col-md-6">
           <div class="thumbnail">
             <img src="imagens/Notebook-Acer-especial-da-Microsoft-bg.jpg"  alt="" class="img-rounded" >
             <div class="caption">
               <h3>Pc Dell Optples I7</h3>
               <p>R$ 3.250,00</p>
               <p>Ou 10X de 325,00 sem juro</p>
               <p><a class="btn btn-success" href="#" role="button">Comprar</a></p>

             </div>
           </div>
         </div>
		</div>

		       <div class="row conteudo">
		         <div class="col-sm-5 col-md-6">
		           <div class="thumbnail">
		             <img src="imagens/Notebook-Acer-especial-da-Microsoft-bg.jpg"  alt="" class="img-rounded" >
		             <div class="caption">
		               <h3>Pc Dell Optples I7</h3>
		               <p>R$ 3.250,00</p>
		               <p>Ou 10X de 325,00 sem juro</p>
		               <p><a class="btn btn-success" href="#" role="button">Comprar</a></p>
		               
		             </div>
		           </div>
		         </div>
				
		         <div class="col-sm-5 col-md-6">
		           <div class="thumbnail">
		             <img src="imagens/Notebook-Acer-especial-da-Microsoft-bg.jpg"  alt="" class="img-rounded" >
		             <div class="caption">
		               <h3>Pc Dell Optples I7</h3>
		               <p>R$ 3.250,00</p>
		               <p>Ou 10X de 325,00 sem juro</p>
		               <p><a class="btn btn-success" href="#" role="button">Comprar</a></p>
		               
		             </div>
		           </div>
		         </div>
		               <div class="row">
		               		<div class="col-md-4 col-md-offset-4">
		               			<ul class="pagination ">
		               			  <li><a href="#">&laquo;</a></li>
		               			  <li><a href="#">1</a></li>
		               			  <li><a href="#">2</a></li>
		               			  <li><a href="#">3</a></li>
		               			  <li><a href="#">4</a></li>
		               			  
		               			  <li><a href="#">&raquo;</a></li>
		               			</ul>
		               		</div>
		         	      
		               </div>	
				</div>

	      <div>

	      </div>
       </div>
     </div>

   
    <script src="https://code.jquery.com/jquery.js"></script>
<script src="css/bootstrap.min.css"></script>	
</body>
</html>





-->


<!--
<h1>Index Application</h1>

<a href="/admin/marcas/index"><input type="button" class="btn btn-primary" value="Marcas" title="Inserir novo produto."></a>	


<a href="/admin/categorias/index"><input type="button" class="btn btn-primary" value="Categorias" title="Inserir novo produto."></a>	

<a href="/admin/tipo-enderecos/index"><input type="button" class="btn btn-primary" value="Tipo endereco" title="Inserir novo produto."></a>	


<a href="/admin/subcategorias/index"><input type="button" class="btn btn-primary" value="Subcategoria" title="Inserir novo produto."></a>		

<a href="/admin/enderecos/index"><input type="button" class="btn btn-primary" value="Endereços" title="Inserir novo produto."></a>	

<a href="/admin/produtos/index"><input type="button" class="btn btn-primary" value="Produtos" title="Inserir novo produto."></a>

-->