<h1>Index Application</h1>
    
<a href="/admin/produtos/index"><input type="button" class="btn btn-primary" value="Produtos" title="Inserir novo produto."></a>	


<a href="/admin/marcas/index"><input type="button" class="btn btn-primary" value="Marcas" title="Inserir novo produto."></a>	


<a href="/admin/categorias/index"><input type="button" class="btn btn-primary" value="Categorias" title="Inserir novo produto."></a>	

<a href="/admin/tipo-enderecos/index"><input type="button" class="btn btn-primary" value="Tipo endereco" title="Inserir novo produto."></a>	


<a href="/admin/sub-categorias/index"><input type="button" class="btn btn-primary" value="Subcategoria" title="Inserir novo produto."></a>	

<a href="/admin/enderecos/index"><input type="button" class="btn btn-primary" value="Endereços" title="Inserir novo produto."></a>	

