<h1>Subcategoria</h1>
<a href="/admin/subcategorias/save"><input type="button" 
   class="btn btn-primary" value="Nova subcategoria" 
   title="Inserir uma nova subcategoria."></a>	
<br><br>

<div class='panel panel-default'>
    <table class="table">
        <thead>
            <tr class="tabela">
                <th>Descrição</th>
            </tr>
        </thead>
        <tbody>
            <?php
            foreach ($subCategorias as $subCategoria) {
                ?>
                <tr>
                    <td><?php echo $subCategoria->descricao; ?></td>

                    <td> 
                        <a href="/admin/subcategorias/save/id/<?= $subCategoria->id_sub_categoria ?>">
                        <span class="glyphicon glyphicon-pencil" 
                        title="Editar registro"></span> </a>

                        <a href="/admin/subcategorias/delete/id/
                        <?= $subCategoria->id_sub_categoria ?>"
                        onclick= "return confirm('Deseja excluir este registro?');">
                        <span class="glyphicon glyphicon-trash" 
                        title="Excluir registro"></span> </a>
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
</div>

<?php
echo $this->paginationControl(
    $subCategorias, 'sliding', 'partial/paginator.phtml', 
    array(
        'route' => 'subCategoria'
    )
);
?>
