<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php
        echo $this->headMeta()
                ->appendName('viewport', 'width=device-width, initial-scale=1.0')
                ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                ->prependStylesheet($this->basePath('css/style.css'))
                ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
                ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
                ->prependStylesheet($this->basePath('css/simple-sidebar.css'))
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()
                ->prependFile($this->basePath('js/bootstrap.min.js'))
                ->prependFile($this->basePath('js/jquery.min.js'))
                ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath('js/html5shiv.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
        ;
        ?>

    </head>
    <body>
        <div id="wrapper">

            <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
                <div class="container">
                    <div class="navbar-header">
                        <a class="navbar-brand" href="/">Home</a>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="#">Dashboard</a></li>
                            <li><a href="#">Settings</a></li>
                            <li><a href="#">Profile</a></li>
                            <li><a href="#">Help</a></li>
                        </ul>
                    </div>

                    <!-- Menu Lateral -->

                    <!-- Sidebar -->
                    <div id="sidebar-wrapper">
                        <ul class="sidebar-nav">
                            <li class="sidebar-brand">
                                <a href="#"> Administração
                                </a>
                            </li>
                            <li>
                                <a href="#">Cadastros</a>
                            </li>
                            <li>
                                <a href="#">Shortcuts</a>
                            </li>
                            <li>
                                <a href="#">Overview</a>
                            </li>
                            <li>
                                <a href="#">Events</a>
                            </li>
                            <li>
                                <a href="#">About</a>
                            </li>
                            <li>
                                <a href="#">Services</a>
                            </li>
                            <li>
                                <a href="#">Contact</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>

            <!-- /#sidebar-wrapper -->

            <!-- Msg Success -->
            <div class="container-fluid">
                <!-- Msg Success -->

                <?php if ($this->flashMessenger()->getSuccessMessages()) { ?>
                    <div class="alert alert-success center">
                        <?php
                        foreach ($this->flashMessenger()->getSuccessMessages() as $msg) {
                            echo $msg;
                        }
                        ?>
                    </div>
                <?php } ?>

                <!-- Msg Error -->

                <?php if ($this->flashMessenger()->getErrorMessages()) { ?>
                    <div class="alert alert-danger center">
                        <?php
                        foreach ($this->flashMessenger()->getErrorMessages() as $msg) {
                            echo $msg;
                        }
                        ?>
                    </div>
                <?php } ?>

                <!-- Msg Infos -->

                <?php if ($this->flashMessenger()->getInfoMessages()) { ?>
                    <div class="alert alert-info center">
                        <?php
                        foreach ($this->flashMessenger()->getInfoMessages() as $msg) {
                            echo $msg;
                        }
                        ?>
                    </div>
                <?php } ?>
            </div>

            <div class="container"><!--Usar container ou content -->
                <?php echo $this->content; ?>
                <hr>
                <footer>
                    <p>&copy; 2005 - <?php echo date('Y') ?> by Zend Technologies Ltd. <?php echo $this->translate('All rights reserved.') ?></p>
                </footer>
            </div> <!-- /container -->
            <?php echo $this->inlineScript() ?>
        </div>
    </body>
</html>
